name: 'Release'
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Use .npmrc
        uses: bduff9/use-npmrc@v1.1
        with:
          dot-npmrc: ${{ secrets.ACO_NPM_AUTH_TOKEN }}
      - uses: askeladdenco/actions/yarn-install@master
        with:
          auth-token: ${{ secrets.ACO_NPM_AUTH_TOKEN }}
      - name: yarn release
        run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACO_NPM_AUTH_TOKEN }}
