name: 'Release'
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: askeladdenco/actions/yarn-install@master
        with:
          auth-token: ${{ secrets.ACO_NPM_AUTH_TOKEN }}
          node-version: 18.0.0

      - name: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_USERCONFIG: ${{ github.workspace }}/.npmrc
        run: |
          echo '//registry.npmjs.org/:_authToken=${{ secrets.ACO_NPM_AUTOMATION_ACCESS_TOKEN }}' > ${{ github.workspace }}/.npmrc
          yarn release
